### ISSUE TITLE
Allow to pass options to pdf-parse-new to lower log level of pdf.js 

### ISSUE THREAD

**Issue by perki** [simonegosetto/pdf-parse-new#2]
For some documents console is showing warning messages.
exemple: `Warning: TT: undefined function: 32`

it would be nice to change the verbosity level of pdf.js which supports `VERBOSITY_LEVELS`

**Comment by simonegosetto** [comment]
@perki thanks for the tip,

let me know if version 1.2.4 works as expected

**Comment by perki** [comment]
@simonegosetto  Thanks for the reactivity .. 

The option is now present at "render_page" level, could you add it "parsing" level ? 
So we could set it simply at parsing? 
```js
const pdfParse = require('pdf-parse-new');
// ....
const pdfParsed = await pdfParse(dataBuffer, { verbosityLevel: 0 }); 
```

**Comment by simonegosetto** [comment]
@perki i'm working on it, i've already manage the verbosityLevel on parsing, but i would like to remove the multi-version mechanism and use the last version of pdf.js. i hope to finish in some days

**Comment by simonegosetto** [comment]
@perki let me know version 1.3.6 works as expected

**Comment by perki** [comment]
@simonegosetto  Perfect 👍🏻 Thanks a lot!
