### ISSUE TITLE
polyfill warnings

### ISSUE THREAD

**Issue by vonGameTheory** [simonegosetto/pdf-parse-new#3]
Always spits out these warnings using node.  ( I'm using node 20.16.0.)  Seems to work ok for what I'm doing anyway.

Warning: Cannot polyfill `DOMMatrix`, rendering may be broken.
Warning: Cannot polyfill `Path2D`, rendering may be broken.

**Comment by simonegosetto** [comment]
@vonGameTheory fix this in v1.3.7
